In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

In [ ]:
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

In [ ]:
charts_path = '/content/drive/My Drive/FOURTH YEAR/CIS 450/charts.csv'

In [ ]:
charts_df = pd.read_csv(charts_path)
charts_df

              date  rank  ... peak-rank weeks-on-board
0       2021-11-06     1  ...         1              3
1       2021-11-06     2  ...         1             16
2       2021-11-06     3  ...         1             14
3       2021-11-06     4  ...         3             19
4       2021-11-06     5  ...         2             18
...            ...   ...  ...       ...            ...
330082  1958-08-04    96  ...        96              1
330083  1958-08-04    97  ...        97              1
330084  1958-08-04    98  ...        98              1
330085  1958-08-04    99  ...        99              1
330086  1958-08-04   100  ...       100              1

[330087 rows x 7 columns]

Here we will work on entity resolution. We are moving the featured artists within the "artist" column into a new column called "FeaturedArtists" within the Charts database.

In [ ]:
def add_featured_artists(x):
  output = 'N/A'
  if 'Featuring' in x:
    output = x[x.index('Featuring'):]
  elif '(feat.' in x:
    output = x[x.index('(feat'):]
  elif '(Feat.' in x:
    output = x[x.index('(Feat'):]
  elif '&' in x:
    output = x[x.index('&'):]
  return output

In [ ]:
def remove_featured_artists(x):
  if 'Featuring' in x:
    x = x[:x.index('Featuring') - 1]
  elif '(feat.' in x:
    x = x[:x.index('(feat') - 1]
  elif '(Feat.' in x:
    x = x[:x.index('(Feat') - 1]
  elif '&' in x:
    x = x[:x.index('&')-1]
  return x

In [ ]:
charts_df['FeaturedArtists'] = charts_df['artist'].apply(add_featured_artists)
charts_df['artist'] = charts_df['artist'].apply(remove_featured_artists)

In [ ]:
# Replace null values
charts_df["last-week"].fillna(0, inplace = True)

In [ ]:
charts_df

              date  rank  ... weeks-on-board FeaturedArtists
0       2021-11-06     1  ...              3             N/A
1       2021-11-06     2  ...             16             N/A
2       2021-11-06     3  ...             14             N/A
3       2021-11-06     4  ...             19             N/A
4       2021-11-06     5  ...             18             N/A
...            ...   ...  ...            ...             ...
330082  1958-08-04    96  ...              1             N/A
330083  1958-08-04    97  ...              1             N/A
330084  1958-08-04    98  ...              1             N/A
330085  1958-08-04    99  ...              1             N/A
330086  1958-08-04   100  ...              1             N/A

[330087 rows x 8 columns]

In [ ]:
spotify_path = '/content/drive/My Drive/FOURTH YEAR/CIS 450/SpotifyFeatures.csv'

In [ ]:
spotify_df = pd.read_csv(spotify_path)
spotify_df

        genre               artist_name  ... time_signature valence
0       Movie            Henri Salvador  ...            4/4   0.814
1       Movie         Martin & les fÃ©es  ...            4/4   0.816
2       Movie           Joseph Williams  ...            5/4   0.368
3       Movie            Henri Salvador  ...            4/4   0.227
4       Movie              Fabien Nataf  ...            4/4   0.390
...       ...                       ...  ...            ...     ...
232720   Soul                     Slave  ...            4/4   0.962
232721   Soul  Jr Thomas & The Volcanos  ...            4/4   0.969
232722   Soul              Muddy Waters  ...            4/4   0.813
232723   Soul                   R.LUM.R  ...            4/4   0.489
232724   Soul            Mint Condition  ...            4/4   0.479

[232725 rows x 18 columns]

Here we will do a similar thing for the Spotify database. We are moving the featured artists within the "track_name" column into a new column called "FeaturedArtists" within the Spotify database.

In [ ]:
def add_featured_artists(x):
  output = 'N/A'
  if '(feat.' in x:
    output = x[x.index('(feat.'):]
  elif '(featuring' in x:
    output = x[x.index('(featuring'):x.index(')') + 1]
  elif 'Featuring' in x:
    output = x[x.index('Featuring'):]
  return output

In [ ]:
def remove_featured_artists(x):
  if '(feat.' in x:
    x = x[:x.index('(feat.') - 1]
  elif '(featuring' in x:
    x = x[:x.index('(featuring') - 1]
  elif 'Featuring' in x:
    x = x[:x.index('Featuring') - 1]
  return x

In [ ]:
spotify_df['featured_artists'] = spotify_df['track_name'].apply(add_featured_artists)
spotify_df['track_name'] = spotify_df['track_name'].apply(remove_featured_artists)

In [ ]:
spotify_df

        genre               artist_name  ... valence featured_artists
0       Movie            Henri Salvador  ...   0.814              N/A
1       Movie         Martin & les fÃ©es  ...   0.816              N/A
2       Movie           Joseph Williams  ...   0.368              N/A
3       Movie            Henri Salvador  ...   0.227              N/A
4       Movie              Fabien Nataf  ...   0.390              N/A
...       ...                       ...  ...     ...              ...
232720   Soul                     Slave  ...   0.962              N/A
232721   Soul  Jr Thomas & The Volcanos  ...   0.969              N/A
232722   Soul              Muddy Waters  ...   0.813              N/A
232723   Soul                   R.LUM.R  ...   0.489              N/A
232724   Soul            Mint Condition  ...   0.479              N/A

[232725 rows x 19 columns]

In [ ]:
spotify_df.to_csv('newSpotifyFeatures.csv', index=False, float_format='%g')

In [ ]:
charts_df.to_csv('newCharts.csv', index=False)